name: core
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h500dc9f_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.14.0=py314hd8ed1ab_102
  - debugpy=1.8.17=py314h93774dc_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h37d8d59_0
  - libcxx=21.1.5=h3d58e20_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.5.2=h750e83c_0
  - liblzma=5.8.1=hd471939_2
  - libmpdec=4.0.0=h6e16a3a_0
  - libsodium=1.0.20=hfdf4475_0
  - libsqlite=3.51.0=h86bffb9_0
  - libzlib=1.3.1=hd23fc13_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h0622a9a_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.4=h230baf5_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.2=pyh145f28c_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py314hd1e8ddb_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.14.0=hf88997e_102_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.14.0=h4df99d1_102
  - python_abi=3.14=8_cp314
  - pyzmq=27.1.0=py312hb7d603e_0
  - readline=8.2=h7cca4af_2
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=hf689a15_2
  - tornado=6.5.2=py314h6482030_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - zeromq=4.3.5=h6c33b1e_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=h8210216_2
prefix: /usr/local/Caskroom/miniconda/base/envs/core
